# Generated by Django 4.1.13 on 2024-05-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_products_reports_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_unit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantities',
            field=models.FloatField(),
        ),
    ]
