# Generated by Django 4.1.13 on 2024-05-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_products_price_unit_alter_products_quantities'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unit', models.FloatField()),
            ],
        ),
    ]
