# Generated by Django 4.1.13 on 2024-05-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_milkprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk',
            name='product_amount',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
